#ifndef ALGORITHM_ALGORITHM_H
#define ALGORITHM_ALGORITHM_H
#include "Algorithm/Search/Find.h"
#include "Algorithm/Sort/Sort.h"
#include "DataStruct/Array/DynArray.h"
#include "DataStruct/Stack/DynStack.h"
#include "DataStruct/List/DoubleList.h"
#include "DataStruct/Queue/DynQueue.h"
#include "DataStruct/Heap/MinHeap.h"
#include "DataStruct/Queue/MinPriorityQueue.h"
#include "DataStruct/Hash/ListHash.h"
#include "DataStruct/Tree/SortedBinaryTree.h"
#include "DataStruct/Tree/SortedBalanceBinaryTree.h"
#include "Algorithm/Graph/BreadthFirstVisit.h"
#include "Algorithm/Graph/DepthFirstVisit.h"
#include "Algorithm/Graph/TopologySort.h"
#include "Algorithm/Graph/StrongConnectGraph.h"
#include "Algorithm/Graph/ShorestPath.h"
#include "Algorithm/Graph/MinGenerateTree.h"
#include "Algorithm/Graph/MaxStream.h"
#include "Algorithm/Char/CharMatch.h"
//#include "HighLevelAlgorithm/CharactersMatch/CharacterMatch.h"
//#include "HighLevelAlgorithm/LinearPlanning/LinearPlanning.h"
//
//#include "BaseStruct/DynArray.h"
//#include "BaseStruct/Hash.h"
//#include "BaseStruct/List.h"
//#include "BaseStruct/MaxHeap.h"
//#include "BaseStruct/MinHeap.h"
//#include "BaseStruct/Queue.h"
//#include "BaseStruct/Stack.h"
//
//#include "HighLevelStruct/Tree/BinaryTree/BinaryTree.h"
//#include "HighLevelStruct/Tree/SortedBinaryTree/SortedBinaryTree.h"
//#include "HighLevelStruct/Tree/SortedAndBalancedBinaryTree/SortedBalanceBinaryTree.h"
//#include "HighLevelStruct/Tree/SortedAndBalancedMuitiTree/SortedBalanceMultiTree.h"
//#include "HighLevelStruct/Graph/Graph.h"
//
//#include "GraphAlgorithms/BreadthFirstVisit.h"
//#include "GraphAlgorithms/DepthFirstVisit.h"
//#include "GraphAlgorithms/MaxStream.h"
//#include "GraphAlgorithms/MinGenerateTree.h"
//#include "GraphAlgorithms/ReverseGraph.h"
//#include "GraphAlgorithms/ShorestPath.h"
//#include "GraphAlgorithms/StrongConnectGraph.h"
//#include "GraphAlgorithms/TopologySort.h"
#endif

